project:
  type: website

execute:
  freeze: auto

website:
  description: "A blog built with Quarto"
  site-url: https://your-website-url.example.com # you must change this appropriately for RSS feeds to work properly
  title: "blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/paolodelia99
      - icon: linkedin
        href: https://www.linkedin.com/in/paolo-d-elia/
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css



